name: Build

on:
  push:
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo CLOUDFLARE_API_URL=${{ secrets.CLOUDFLARE_API_URL }} >> .env
          echo CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID}} >> .env
          echo CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY}} >> .env
          echo CONTENT_KV_ID=${{ secrets.CONTENT_KV_ID}} >> .env
          echo MAP_TILER_ACCESS_TOKEN=${{ secrets.MAP_TILER_ACCESS_TOKEN}} >> .env

      - name: Execute build
        run: |
          npm install
          npm run build:hikes
          npm run build:recipes
          npm run build:search
          npm run build:site

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Commit
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Bill Beckelman'
          git config --global user.email 'bill@beckelman.net'
          git add .
          git commit -am "[automated commit] Updated readmes as needed."
          git push
