name: Build hikes readme

on:
  push:
    paths:
      - 'hikes/**'
      - '!hikes/*.geojson'
      - '!hikes/readme.md'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - uses: actions/checkout@v2
      
      - run: npm install
      - run: npm run build:hikes
      
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Commit
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Bill Beckelman'
          git config --global user.email 'bill@beckelman.net'
          git commit -am "[automated commit] Updated hikes readme and geojson"
          git push
