name: Build

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - uses: actions/checkout@v2
      
      - name: Execute build
        run: | 
          npm install
          npm run build:hikes
          npm run build:recipes
          npm run build:search
          npm run build:meta
      
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Commit
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Bill Beckelman'
          git config --global user.email 'bill@beckelman.net'
          git add .
          git commit -am "[automated commit] Updated readmes and search.json as needed."
          git push
