name: Publish hikes readme.md

on:
  push:
    branches: [ main ]
    paths:
      - 'hikes/**'
      - '!hikes/*.geojson'
      - '!hikes/readme.md'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: node ./build/publish-hikes-readme.js
      - name: Commit report
        run: |
          git config --global user.name 'Bill Beckelman'
          git config --global user.email 'bill@beckelman.net'
          git commit -am "Updated hikes readme"
          git push
