# This is a basic workflow to help you get started with Actions

name: Publish hikes readme.md

on:
  push:
    branches: [ main ]
    paths:
      - 'hikes/**'
      - '!hikes/*.geojson'
      - '!hikes/readme.md'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: node ./build/create-hikes-readme.js
